language: java
jdk: 
  - oraclejdk8
  - oraclejdk9
cache:
  directories:
  - $HOME/.m2
install: true
script: ./mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script: ./mvn test -B -V
script: ./mvn site -DskipTests=true -Dmaven.javadoc.skip=false -B -V
