language: java
jdk: 
  - oraclejdk8
  - oraclejdk9
cache:
  directories:
  - $HOME/.m2
install: true
script: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V 
        mvn test -B -V
        mvn site -DskipTests=true -Dmaven.javadoc.skip=false -B -V
